### ISSUE TITLE
Hooks function functionality

### ISSUE THREAD

**Issue by abaicus** [Codeinwp/orbit-fox#6]
https://github.com/Codeinwp/orbit-fox/pull/5

I've added a social sharing module in the pull request above. There might be an issue with the hooks functionality. Right now, the markup that the module adds is not displayed on the front end. 

If you add a `die();` after the `social-sharing-tpl.php` view files' code, it adds it to the markup of the page. 

Am I doing something wrong or is something broken? 

@preda-bogdan

**Comment by preda-bogdan** [comment]
@abaicus i've tested with your module, you are doing a return you need to echo the render. you will then see that the html is inserted inside the footer area. I think you should use another hook or a filter.
