### ISSUE TITLE
Callback functions for options

### ISSUE THREAD

**Issue by abaicus** [Codeinwp/orbit-fox#7]
@preda-bogdan  @ineagu @selul 

I'm thinking we might at some point need to add contextual settings regarding plugins and themes. For example I might want to add an option strictly available when on Hestia, or options regarding WooCommerce.

What do you think?

**Comment by preda-bogdan** [comment]
@abaicus I think you can do that just by using filters

**Comment by selul** [comment]
do you mean load modules if some plugins/themes are installed ?
